### ISSUE TITLE
Clarify the need of the fine-grained indicators

### ISSUE THREAD

**Issue by Spoonbender** [wasm-rs/cargo-metadata#2]
The `targets` key under `[package.metadata.wasm.rs]` lets us specify which wasm targets are *supported*. It seems to me that stating that a specific target is supported should be a strong enough statement, which conflicts with the ability to specify the fine-grained indicators. Examples:
- Does it make sense that `wasm32-unknown-unknown` is supported but `compiles = false`?
- Does it make sense that `wasm32-unknown-unknown` is supported but `works = false`?

It _might_ make sense that a target is supported but the tests don't pass because of <reasons> (e.g. there is some issue causing a test to fail on `wasm32-unknown-unknown` but in practice the crate works), but I feel this too is not really needed.

Additionally, is there a real need to specify `compiles` and `passes-tests` if these values can actually be computed by attempting to compile and to run the tests?

**Comment by yrashk** [comment]
I guess `compiles = false` doesn't make much sense. What if we keep `passes-tests` and `limited-functionality`? And perhaps runtime information (browsers & other wasm runtimes) when this comes to fruition?

Edit: or even just `limited-functionality` and (future) runtime matrix.

**Comment by yrashk** [comment]
Also, what I think is useful in fine-grained targets is features (#1), this can be useful for enabling particular targets.

**Comment by Spoonbender** [comment]
Absolutely, we need to have fine-grained targets specification for features and other future things, as well as the limited functionality notice. 
My issue refers specifically to `compiles`, `passes-tests` and `works`

**Comment by yrashk** [comment]
Let's remove `compiles`, `passes-tests` and `works`, then? I agree they are kind of dubious value especially if they aren't reflecting reality.

**Comment by Spoonbender** [comment]
@yrashk yup, PR sent
