### ISSUE TITLE
Proposal: markdown description of the WASM support notes 

### ISSUE THREAD

**Issue by Spoonbender** [wasm-rs/cargo-metadata#5]
The inspiration for this proposal stems from:
1. The `limited-functionality` field
2. The way the `readme` field works in crate manifests (`cargo.toml` files), see: https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field

I'm proposing we add a field similar to the `[package] readme` field that lets the author elaborate on their crate's WASM support in a markdown file.
Something like `wasm-readme` which the author would point to a markdown file in their repo.
If present, wasm-rs will interpret it as markdown and render it on the crate's page.

**Comment by yrashk** [comment]
I like it.

**Comment by yrashk** [comment]
Addressed in #6
